// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (id, user_id, role, email, family_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, role, email, family_id, token_hash, expires_at, used_at, revoked_at, created_at
`

type CreateAuthSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	Email     string             `json:"email"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.Role,
		arg.Email,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Email,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthSessionByHash = `-- name: GetAuthSessionByHash :one
SELECT id, user_id, role, email, family_id, token_hash, expires_at, used_at, revoked_at, created_at FROM auth_sessions
WHERE token_hash = $1
`

func (q *Queries) GetAuthSessionByHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Email,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthSessionForUpdate = `-- name: GetAuthSessionForUpdate :one
SELECT id, user_id, role, email, family_id, token_hash, expires_at, used_at, revoked_at, created_at FROM auth_sessions
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetAuthSessionForUpdate(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionForUpdate, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Email,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthSessionUsed = `-- name: MarkAuthSessionUsed :execrows
UPDATE auth_sessions
SET used_at = $2
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL
`

type MarkAuthSessionUsedParams struct {
	ID     pgtype.UUID        `json:"id"`
	UsedAt pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkAuthSessionUsed(ctx context.Context, arg MarkAuthSessionUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAuthSessionUsed, arg.ID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSessionByHash = `-- name: RevokeAuthSessionByHash :execrows
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE token_hash = $1 AND revoked_at IS NULL
`

type RevokeAuthSessionByHashParams struct {
	TokenHash string             `json:"token_hash"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthSessionByHash(ctx context.Context, arg RevokeAuthSessionByHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionByHash, arg.TokenHash, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSessionFamily = `-- name: RevokeAuthSessionFamily :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE family_id = $1
`

type RevokeAuthSessionFamilyParams struct {
	FamilyID  pgtype.UUID        `json:"family_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAuthSessionFamily(ctx context.Context, arg RevokeAuthSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionFamily, arg.FamilyID, arg.RevokedAt)
	return err
}
