// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, name, email, birth_date, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, birth_date, password, created_at
`

type CreateClientParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	BirthDate pgtype.Date `json:"birth_date"`
	Password  string      `json:"password"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.BirthDate,
		arg.Password,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.BirthDate,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :execrows
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClientByEmail = `-- name: GetClientByEmail :one
SELECT id, name, email, birth_date, password, created_at FROM clients
WHERE email = $1
`

func (q *Queries) GetClientByEmail(ctx context.Context, email string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByEmail, email)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.BirthDate,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, email, birth_date, password, created_at FROM clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.BirthDate,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, email, birth_date, password, created_at FROM clients
ORDER BY created_at DESC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.BirthDate,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $2, email = $3, birth_date = $4, password = $5
WHERE id = $1
RETURNING id, name, email, birth_date, password, created_at
`

type UpdateClientParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	BirthDate pgtype.Date `json:"birth_date"`
	Password  string      `json:"password"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.BirthDate,
		arg.Password,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.BirthDate,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
