// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	Email     string             `json:"email"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Client struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Document  string             `json:"document"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID              pgtype.UUID        `json:"id"`
	ProviderID      pgtype.UUID        `json:"provider_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	PriceCents      int32              `json:"price_cents"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
