// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (id, name, email, document, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, document, password, created_at
`

type CreateProviderParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Document string      `json:"document"`
	Password string      `json:"password"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Document,
		arg.Password,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM providers
WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderByEmail = `-- name: GetProviderByEmail :one
SELECT id, name, email, document, password, created_at FROM providers
WHERE email = $1
`

func (q *Queries) GetProviderByEmail(ctx context.Context, email string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByEmail, email)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, email, document, password, created_at FROM providers
WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, email, document, password, created_at FROM providers
ORDER BY created_at DESC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Document,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name = $2, email = $3, document = $4, password = $5
WHERE id = $1
RETURNING id, name, email, document, password, created_at
`

type UpdateProviderParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Document string      `json:"document"`
	Password string      `json:"password"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Document,
		arg.Password,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
