// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (provider_id, name, description, price_cents, duration_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, name, description, price_cents, duration_minutes, created_at
`

type CreateServiceParams struct {
	ProviderID      pgtype.UUID `json:"provider_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	PriceCents      int32       `json:"price_cents"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ProviderID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.DurationMinutes,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, provider_id, name, description, price_cents, duration_minutes, created_at FROM services
WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, provider_id, name, description, price_cents, duration_minutes, created_at FROM services
ORDER BY created_at DESC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.DurationMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProviderID = `-- name: ListServicesByProviderID :many
SELECT id, provider_id, name, description, price_cents, duration_minutes, created_at FROM services
WHERE provider_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServicesByProviderID(ctx context.Context, providerID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByProviderID, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.DurationMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, description = $3, price_cents = $4, duration_minutes = $5
WHERE id = $1
RETURNING id, provider_id, name, description, price_cents, duration_minutes, created_at
`

type UpdateServiceParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	PriceCents      int32       `json:"price_cents"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.DurationMinutes,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}
